CREATE DATABASE ATTORESEARCH;

CREATE TABLE HOST (
	`id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`ip` VARCHAR(100) NOT NULL UNIQUE,
	`name` VARCHAR(100) NOT NULL UNIQUE,
	`created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,	
	`alive_status` TINYINT(1),
	`alive_time` DATETIME
);

INSERT INTO HOST(NAME, IP) VALUES("local", "127.0.0.1");
INSERT INTO HOST(NAME, IP) VALUES("naver", "223.130.200.107");
INSERT INTO HOST(NAME, IP) VALUES("google", "142.250.207.46");
INSERT INTO HOST(NAME, IP) VALUES("daum", "121.53.105.193");

COMMIT;